version: "3.9"

services:
  postgres:
    image: "postgres:13.3-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - ".postgres-env"
    ports:
      - 5432:5432

  api:
    build: .
    depends_on:
      - postgres
    command: node src/index.js
    ports:
      - "80:1337"
    deploy:
      replicas: 1
    env_file:
      - ".env"

volumes:
  postgres:
